In [1]:
# DEPENDENCIES
import pandas as pd
from sqlalchemy import create_engine
import pymongo
import json

In [2]:
# RESOURCES FILES AND CONVERTING INTO DATAFRAME
csv_CAvideos = 'Resources/CAvideos.csv'
csv_GBvideos = 'Resources/GBvideos.csv'
csv_USvideos = 'Resources/USvideos.csv'

CAvideos_data_df = pd.read_csv(csv_CAvideos)
GBvideos_data_df = pd.read_csv(csv_GBvideos)
USvideos_data_df = pd.read_csv(csv_USvideos)

### CANADA TRENDING VIDEOS

In [3]:
CAvideos_data_df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...

In [67]:
# CLEANING TABLES TO GIVE COLUMNS NEEDED
clean_cavideos_df = CAvideos_data_df[['video_id', 'title', 'channel_title', 'category_id', 'views', 'likes', 'dislikes', 'comment_count']]
clean_cavideos_df.insert(1,'country', 'CA')
clean_cavideos_df

,video_id,country,title,channel_title,category_id,views,likes,dislikes,comment_count
0,n1WpP7iowLc,CA,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,17158579,787425,43420,125882
1,0dBIkQ4Mz1M,CA,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,1014651,127794,1688,13030
2,5qpjK5DgCt4,CA,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,3191434,146035,5339,8181
3,d380meD0W0M,CA,I Dare You: GOING BALD!?,nigahiga,24,2095828,132239,1989,17518
4,2Vv-BfVoq4g,CA,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,33523622,1634130,21082,85067
...,...,...,...,...,...,...,...,...,...
40876,sGolxsMSGfQ,CA,HOW2: How to Solve a Mystery,Annoying Orange,24,80685,1701,99,1312
40877,8HNuRNi8t70,CA,Eli Lik Lik Episode 13 Partie 01,Elhiwar Ettounsi,24,103339,460,66,51
40878,GWlKEM3m2EE,CA,KINGDOM HEARTS III – SQUARE ENIX E3 SHOWCASE 2...,Kingdom Hearts,20,773347,25900,224,3881
40879,lbMKLzQ4cNQ,CA,Trump Advisor Grovels To Trudeau,The Young Turks,25,115225,2115,182,1672
40880,POTgw38-m58,CA,【完整版】遇到恐怖情人該怎麼辦？2018.06.13小明星大跟班,我愛小明星大跟班,24,107392,300,62,251

In [5]:
# READ THE JSON FILE
ca_json_file = "Resources/CA_category_id.json"

In [6]:
# CONVERT JSON FILE INTO A PANDAS DATAFRAME
ca_json_df = pd.read_json(ca_json_file)
ca_json_df.head()

,kind,etag,items
0,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."
1,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."
2,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."
3,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."
4,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."

In [7]:
list_countries=["Resources/CA_category_id.json"]
category = []

for country in list_countries:
    json_data = json.load(open(country,'r'))
    for data in json_data['items']:
        category.append([data['id'], data['snippet']['title']])

category

[['1', 'Film & Animation'],
 ['2', 'Autos & Vehicles'],
 ['10', 'Music'],
 ['15', 'Pets & Animals'],
 ['17', 'Sports'],
 ['18', 'Short Movies'],
 ['19', 'Travel & Events'],
 ['20', 'Gaming'],
 ['21', 'Videoblogging'],
 ['22', 'People & Blogs'],
 ['23', 'Comedy'],
 ['24', 'Entertainment'],
 ['25', 'News & Politics'],
 ['26', 'Howto & Style'],
 ['27', 'Education'],
 ['28', 'Science & Technology'],
 ['30', 'Movies'],
 ['31', 'Anime/Animation'],
 ['32', 'Action/Adventure'],
 ['33', 'Classics'],
 ['34', 'Comedy'],
 ['35', 'Documentary'],
 ['36', 'Drama'],
 ['37', 'Family'],
 ['38', 'Foreign'],
 ['39', 'Horror'],
 ['40', 'Sci-Fi/Fantasy'],
 ['41', 'Thriller'],
 ['42', 'Shorts'],
 ['43', 'Shows'],
 ['44', 'Trailers']]

In [48]:
# USE THE MAP FUNCTION TO ASSIGN CATEGORY ID WITH A CATEGORY NAME BASED ON THE JSON FILE
categoryCA_map={1:'Film & Animation', 2:'Autos & Vehicles', 10:'Music', 15:'Pets & Animals', 17:'Sports',18: 'Short Movies',
               19:'Travel & Events', 20:'Gaming',21: 'Videoblogging',22: 'People & Blogs',23: 'Comedy',24: 'Entertainment',
               25: 'News & Politics',26: 'Howto & Style',27: 'Education', 28: 'Science & Technology',29: 'Nonprofits & Activism',30: 'Movies', 
               31: 'Anime/Animation', 32: 'Action/Adventure',33: 'Classics', 34:'Comedy', 35: 'Documentary', 36: 'Drama',
               37: 'Family', 38: 'Foreign', 39: 'Horror', 40: 'Sci-Fi/Fantasy', 41: 'Thriller', 42: 'Shorts', 43: 'Shows', 44: 'Trailers'}

clean_cavideos_df['category_name'] = clean_cavideos_df['category_id'].map(categoryCA_map)
clean_cavideos_df.head()

# clean_cavideos_df = clean_cavideos_df[['video_id', 'country', 'title', 'channel_title', 'category_id', 'category_name', 'views', 'likes', 'dislikes', 'comment_count']]
# clean_cavideos_df

,video_id,country,title,channel_title,category_id,category_name,views,likes,dislikes,comment_count
0,n1WpP7iowLc,CA,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,Music,17158579,787425,43420,125882
1,0dBIkQ4Mz1M,CA,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,Comedy,1014651,127794,1688,13030
2,5qpjK5DgCt4,CA,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,Comedy,3191434,146035,5339,8181
3,d380meD0W0M,CA,I Dare You: GOING BALD!?,nigahiga,24,Entertainment,2095828,132239,1989,17518
4,2Vv-BfVoq4g,CA,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,Music,33523622,1634130,21082,85067

In [50]:
# TOP 10 TRENDNING VIDEOS
top10_videos_cols = ['video_id', 'title', 'channel_title', 'views',  'category_id', 'category_name', 'country']
top10_videos_ca = clean_cavideos_df[top10_videos_cols].copy()
top10_videos_ca.drop_duplicates('video_id', inplace = True)
top10_videos_ca = top10_videos_ca.sort_values(by='views', ascending=False)
top10_videos_ca = top10_videos_ca.reset_index(drop=True)
top10_videos_ca.head(10)

,video_id,title,channel_title,views,category_id,category_name,country
0,7C2z4GqqS5E,BTS (방탄소년단) 'FAKE LOVE' Official MV,ibighit,39349927,10,Music,CA
1,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,37736281,24,Entertainment,CA
2,wfWkmURBNv8,Ozuna x Romeo Santos - El Farsante Remix,Ozuna,37597115,10,Music,CA
3,2Vv-BfVoq4g,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,33523622,10,Music,CA
4,xmU0s2QtaEY,Swag Se Swagat Song | Tiger Zinda Hai | Salman...,YRF,24939458,10,Music,CA
5,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24784863,24,Entertainment,CA
6,FCfP7v9x8HI,Prince Royce - El Clavo (Official Video),PrinceRoyceVEVO,23869973,10,Music,CA
7,1J76wN0TPI4,Sanju | Official Trailer | Ranbir Kapoor | Raj...,FoxStarHindi,21739537,24,Entertainment,CA
8,BhIEIO0vaBE,To Our Daughter,Kylie Jenner,20921796,22,People & Blogs,CA
9,QwievZ1Tx-8,Marvel Studios' Avengers: Infinity War - Offic...,Marvel Entertainment,19716689,24,Entertainment,CA

In [10]:
# TOP 10 HIGHEST LIKES VIDEOS
top_liked_videos = clean_cavideos_df[['country', 'video_id', 'title', 'channel_title', 'views','likes', 'category_id','category_name']].sort_values('likes', ascending=False)
top_liked_videos.drop_duplicates('video_id', inplace=True)
top_liked_videos.reset_index(drop=True)
top_liked_videos.head(10)

,country,video_id,title,channel_title,views,likes,category_id,category_name
36453,CA,7C2z4GqqS5E,BTS (방탄소년단) 'FAKE LOVE' Official MV,ibighit,80738011,5053338,10,Music
34361,CA,VYOjWnS4cMY,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,98938809,3037318,10,Music
5900,CA,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,137843120,3014479,24,Entertainment
4699,CA,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,89930713,2606665,24,Entertainment
2873,CA,kTlv5_Bs8aw,BTS (방탄소년단) 'MIC Drop (Steve Aoki Remix)' Offi...,ibighit,27670973,2542863,10,Music
20055,CA,xpVfcZ0ZcFM,Drake - God’s Plan,DrakeVEVO,47362934,2469057,10,Music
33633,CA,p8npDG2ulKQ,BTS (방탄소년단) LOVE YOURSELF 轉 Tear 'Singularity'...,ibighit,18574625,2407419,10,Music
21466,CA,OK3GJ0WIQ8s,j-hope 'Daydream (백일몽)' MV,ibighit,15777624,2392594,10,Music
30900,CA,ffxKSjUwKdU,Ariana Grande - No Tears Left To Cry,ArianaGrandeVevo,45998071,2195120,10,Music
39208,CA,aJOTlE1K90k,Maroon 5 - Girls Like You ft. Cardi B,Maroon5VEVO,47778378,2178332,10,Music

In [11]:
# TOP 10 HIGHEST COMMENT COUNT VIDEOS
highest_comment_count = clean_cavideos_df[['country','video_id', 'title', 'channel_title', 'comment_count']].sort_values('comment_count', ascending=False)
highest_comment_count.drop_duplicates('video_id', inplace=True)
highest_comment_count.reset_index(drop=True)
highest_comment_count.head(10)

,country,video_id,title,channel_title,comment_count
36453,CA,7C2z4GqqS5E,BTS (방탄소년단) 'FAKE LOVE' Official MV,ibighit,1114800
4996,CA,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,827755
14852,CA,oWjxSkJpxFU,Suicide: Be Here Tomorrow.,Logan Paul Vlogs,625010
2873,CA,kTlv5_Bs8aw,BTS (방탄소년단) 'MIC Drop (Steve Aoki Remix)' Offi...,ibighit,519092
34599,CA,32sYGCOYJUM,CHẠY NGAY ĐI | RUN NOW | SƠN TÙNG M-TP | Offic...,Sơn Tùng M-TP Official,445251
21466,CA,OK3GJ0WIQ8s,j-hope 'Daydream (백일몽)' MV,ibighit,437036
29241,CA,FhllRWReNEE,Melting Every Lipstick From Sephora Together,Safiya Nygaard,349112
4699,CA,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,347982
33633,CA,p8npDG2ulKQ,BTS (방탄소년단) LOVE YOURSELF 轉 Tear 'Singularity'...,ibighit,340125
34361,CA,VYOjWnS4cMY,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,319502

In [43]:
# HOW MANY VIDEOS FALL INTO EACH CATEGORY
ca_category_counts = clean_cavideos_df.groupby(['category_name']).size()
ca_category_counts = clean_cavideos_df.groupby(['category_name']).size().reset_index(name='counts')
ca_category_counts

            category_name  counts
0        Autos & Vehicles     353
1                  Comedy    3773
2               Education     991
3           Entertainment   13451
4        Film & Animation    2060
5                  Gaming    1344
6           Howto & Style    2007
7                  Movies       6
8                   Music    3731
9         News & Politics    4159
10  Nonprofits & Activism      74
11         People & Blogs    4105
12         Pets & Animals     369
13   Science & Technology    1155
14                  Shows     124
15                 Sports    2787
16        Travel & Events     392

### US TRENDING VIDEOS

In [77]:
USvideos_df.head()

,video_id,country,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,category_name
0,2kyS6SvSYSE,US,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,People & Blogs
1,1ZAPwfrtAFY,US,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John...",Entertainment
2,5qpjK5DgCt4,US,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,Comedy
3,puqaWrEC7tY,US,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...,Entertainment
4,d380meD0W0M,US,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,Entertainment

In [14]:
us_json_file = 'Resources/US_category_id.json'
US_category_json_df = pd.read_json(us_json_file)
US_category_json_df.head()

,kind,etag,items
0,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
1,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
2,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
3,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
4,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."

In [15]:
USvideos_df = USvideos_data_df[['video_id', 'trending_date', 'title', 'channel_title', 'category_id',
       'publish_time', 'tags', 'views', 'likes', 'dislikes', 'comment_count',
       'thumbnail_link', 'comments_disabled', 'ratings_disabled',
       'video_error_or_removed', 'description']].copy()

In [16]:
USvideos_df.insert(1,'country','US')
USvideos_df.head()

,video_id,country,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,2kyS6SvSYSE,US,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...
1,1ZAPwfrtAFY,US,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John..."
2,5qpjK5DgCt4,US,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,puqaWrEC7tY,US,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...
4,d380meD0W0M,US,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...

In [51]:
top_trending_videos_col = ['video_id','title', 'views', 'trending_date', 'category_id', 'country']
top_trending_videos = USvideos_df[top_trending_videos_col].copy()
top_trending_videos.drop_duplicates('video_id', inplace=True)
top_trending_videos = top_trending_vidoes.sort_values(by= 'views', ascending=False )
top_trending_videos = top_trending_vidoes.reset_index(drop=True)
top_trending_videos.head(10)

,video_id,title,views,trending_date,category_id,country
0,-BQJo3vK8O8,Maluma - El Préstamo (Official Video),48431654,18.15.03,10,US
1,7C2z4GqqS5E,BTS (방탄소년단) 'FAKE LOVE' Official MV,39349927,18.19.05,10,US
2,i0p1bmr0EmE,TWICE What is Love? M/V,38873543,18.14.04,10,US
3,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,37736281,17.30.11,24,US
4,2Vv-BfVoq4g,Ed Sheeran - Perfect (Official Music Video),33523622,17.14.11,10,US
5,VYOjWnS4cMY,Childish Gambino - This Is America (Official V...,31648454,18.08.05,10,US
6,u9Mv98Gr5pY,VENOM - Official Trailer (HD),27973210,18.25.04,24,US
7,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,24782158,17.07.12,24,US
8,U9BwWKXjVaI,Drake - Nice For What,24421448,18.14.04,10,US
9,1J76wN0TPI4,Sanju | Official Trailer | Ranbir Kapoor | Raj...,23758250,18.01.06,24,US

In [54]:
top_liked_videos_col =['video_id','title', 'likes', 'category_id', 'country']
top_liked_videos = USvideos_df[top_liked_videos_col].copy()
top_liked_videos.drop_duplicates('video_id', inplace=True)
top_liked_videos = top_liked_vidoes.sort_values(by= 'likes', ascending=False )
top_liked_videos = top_liked_vidoes.reset_index(drop=True)
top_liked_videos.head(10)

,video_id,title,likes,category_id,country
0,7C2z4GqqS5E,BTS (방탄소년단) 'FAKE LOVE' Official MV,3880071,10,US
1,kTlv5_Bs8aw,BTS (방탄소년단) 'MIC Drop (Steve Aoki Remix)' Offi...,2055137,10,US
2,OK3GJ0WIQ8s,j-hope 'Daydream (백일몽)' MV,2050527,10,US
3,p8npDG2ulKQ,BTS (방탄소년단) LOVE YOURSELF 轉 Tear 'Singularity'...,1956202,10,US
4,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,1735895,24,US
5,2Vv-BfVoq4g,Ed Sheeran - Perfect (Official Music Video),1634124,10,US
6,kX0vO4vlJuU,BTS (방탄소년단) 'Euphoria : Theme of LOVE YOURSELF...,1572997,10,US
7,D_6QmL6rExk,BTS (방탄소년단) 'FAKE LOVE' Official MV (Extended ...,1437859,10,US
8,VYOjWnS4cMY,Childish Gambino - This Is America (Official V...,1405355,10,US
9,8O_MwlZ2dEg,j-hope 'Airplane' MV,1401915,10,US

In [55]:
Highest_comment_count_videos_col = ['video_id','title','comment_count', 'country']
Highest_comment_count_videos = USvideos_df[Highest_comment_count_videos_col].copy()
Highest_comment_count_videos.drop_duplicates('video_id', inplace=True)
Highest_comment_count_videos = Highest_comment_count_vidoes.sort_values(by= 'comment_count', ascending=False )
Highest_comment_count_videos = Highest_comment_count_vidoes.reset_index(drop=True)
Highest_comment_count_videos.head(10)

,video_id,title,comment_count,country
0,QwZT7T-TXT0,So Sorry.,733373,US
1,7C2z4GqqS5E,BTS (방탄소년단) 'FAKE LOVE' Official MV,692305,US
2,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,462103,US
3,_5d-sQ7Fh5M,LOGAN PAUL IS BACK!,432534,US
4,kTlv5_Bs8aw,BTS (방탄소년단) 'MIC Drop (Steve Aoki Remix)' Offi...,395562,US
5,OK3GJ0WIQ8s,j-hope 'Daydream (백일몽)' MV,387384,US
6,oWjxSkJpxFU,Suicide: Be Here Tomorrow.,363133,US
7,FhllRWReNEE,Melting Every Lipstick From Sephora Together,321455,US
8,p8npDG2ulKQ,BTS (방탄소년단) LOVE YOURSELF 轉 Tear 'Singularity'...,285583,US
9,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,241237,US

In [56]:
list_contries =[us_json_file]
US_category=[]

for country in list_contries:
    json_data = json.load(open(country,'r'))
    for data in json_data['items']:
        US_category.append([data['id'], data['snippet']['title']])
US_category

[['1', 'Film & Animation'],
 ['2', 'Autos & Vehicles'],
 ['10', 'Music'],
 ['15', 'Pets & Animals'],
 ['17', 'Sports'],
 ['18', 'Short Movies'],
 ['19', 'Travel & Events'],
 ['20', 'Gaming'],
 ['21', 'Videoblogging'],
 ['22', 'People & Blogs'],
 ['23', 'Comedy'],
 ['24', 'Entertainment'],
 ['25', 'News & Politics'],
 ['26', 'Howto & Style'],
 ['27', 'Education'],
 ['28', 'Science & Technology'],
 ['29', 'Nonprofits & Activism'],
 ['30', 'Movies'],
 ['31', 'Anime/Animation'],
 ['32', 'Action/Adventure'],
 ['33', 'Classics'],
 ['34', 'Comedy'],
 ['35', 'Documentary'],
 ['36', 'Drama'],
 ['37', 'Family'],
 ['38', 'Foreign'],
 ['39', 'Horror'],
 ['40', 'Sci-Fi/Fantasy'],
 ['41', 'Thriller'],
 ['42', 'Shorts'],
 ['43', 'Shows'],
 ['44', 'Trailers']]

In [58]:
US_category_map={1: 'Film & Animation', 2: 'Autos & Vehicles', 10: 'Music', 15: 'Pets & Animals', 17: 'Sports',
                 18: 'Short Movies', 19: 'Travel & Events', 20: 'Gaming', 21: 'Videoblogging',22: 'People & Blogs'
                 ,23: 'Comedy',24: 'Entertainment',25: 'News & Politics',26: 'Howto & Style',27:'Education',
                  28: 'Science & Technology',29: 'Nonprofits & Activism',30: 'Movies',31: 'Anime/Animation',
                  32: 'Action/Adventure',33: 'Classics',34: 'Comedy',35: 'Documentary',36: 'Drama',37: 'Family',
                 38: 'Foreign',39: 'Horror', 40: 'Sci-Fi/Fantasy',41: 'Thriller',42: 'Shorts',43: 'Shows',44: 'Trailers'}

USvideos_df['category_name']= USvideos_df['category_id'].map(US_category_map)
USvideos_df.head()

,video_id,country,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,category_name
0,2kyS6SvSYSE,US,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,People & Blogs
1,1ZAPwfrtAFY,US,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John...",Entertainment
2,5qpjK5DgCt4,US,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,Comedy
3,puqaWrEC7tY,US,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...,Entertainment
4,d380meD0W0M,US,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,Entertainment

In [59]:
category_videos_col = ['video_id', 'category_id','category_name','country']
category_videos = USvideos_df[category_videos_col].copy()
category_videos.drop_duplicates('video_id', inplace=True)
category_videos = category_vidoes.reset_index(drop=True)
category_videos.head()

      video_id  category_id   category_name country  counts_x  counts_y
0  2kyS6SvSYSE           22  People & Blogs      US      3210      3210
1  0mlNzVSJrT0           22  People & Blogs      US      3210      3210
2  STI2fI7sKMo           22  People & Blogs      US      3210      3210
3  KODzih-pYlU           22  People & Blogs      US      3210      3210
4  8mhTWqWlQzU           22  People & Blogs      US      3210      3210

In [60]:
count_category_id = USvideos_df.groupby(['category_name']).size().reset_index(name='counts')
count_category_id

            category_name  counts
0        Autos & Vehicles     384
1                  Comedy    3457
2               Education    1656
3           Entertainment    9964
4        Film & Animation    2345
5                  Gaming     817
6           Howto & Style    4146
7                   Music    6472
8         News & Politics    2487
9   Nonprofits & Activism      57
10         People & Blogs    3210
11         Pets & Animals     920
12   Science & Technology    2401
13                  Shows      57
14                 Sports    2174
15        Travel & Events     402

### GREAT BRITAIN TRENDING VIDEOS

In [61]:
GBvideos_data_df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,Jw1Y-zhQURU,17.14.11,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515,55681,10247,9479,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,False,False,Click here to continue the story and make your...
1,3s1rvMFUweQ,17.14.11,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632,25561,2294,2757,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,False,False,Musical guest Taylor Swift performs …Ready for...
2,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787420,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
3,PUTEiSjKwJU,17.14.11,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833,193,12,37,https://i.ytimg.com/vi/PUTEiSjKwJU/default.jpg,False,False,False,Salford drew 4-4 against the Class of 92 and F...
4,rHwDegptbI4,17.14.11,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25,2017-11-13T01:45:13.000Z,[none],9815,30,2,30,https://i.ytimg.com/vi/rHwDegptbI4/default.jpg,False,False,False,Dashcam captures truck's near miss with child ...

In [28]:
GB_json_file = "Resources/GB_category_id.json"
GB_json_df=pd.read_json(GB_json_file)
GB_json_df.head()

,kind,etag,items
0,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
1,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
2,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
3,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
4,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."

In [31]:
list_countries = ["Resources/GB_category_id.json"]
category = []
for country in list_countries:
    json_data = json.load(open(country,'r'))
    for data in json_data['items']:
        category.append([data['id'],data['snippet']['title']])

category

[['1', 'Film & Animation'],
 ['2', 'Autos & Vehicles'],
 ['10', 'Music'],
 ['15', 'Pets & Animals'],
 ['17', 'Sports'],
 ['18', 'Short Movies'],
 ['19', 'Travel & Events'],
 ['20', 'Gaming'],
 ['21', 'Videoblogging'],
 ['22', 'People & Blogs'],
 ['23', 'Comedy'],
 ['24', 'Entertainment'],
 ['25', 'News & Politics'],
 ['26', 'Howto & Style'],
 ['27', 'Education'],
 ['28', 'Science & Technology'],
 ['30', 'Movies'],
 ['31', 'Anime/Animation'],
 ['32', 'Action/Adventure'],
 ['33', 'Classics'],
 ['34', 'Comedy'],
 ['35', 'Documentary'],
 ['36', 'Drama'],
 ['37', 'Family'],
 ['38', 'Foreign'],
 ['39', 'Horror'],
 ['40', 'Sci-Fi/Fantasy'],
 ['41', 'Thriller'],
 ['42', 'Shorts'],
 ['43', 'Shows'],
 ['44', 'Trailers']]

In [33]:
gb_cols = ['video_id', 'trending_date', 'title', 'channel_title', 'category_id',
       'publish_time', 'tags', 'views', 'likes', 'dislikes', 'comment_count',
       'thumbnail_link', 'comments_disabled', 'ratings_disabled',
       'video_error_or_removed', 'description']
GB_df = GBvideos_data_df[gb_cols].copy()
GB_df.insert(1,'country','GB')
GB_df.head()

,video_id,country,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,Jw1Y-zhQURU,GB,17.14.11,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515,55681,10247,9479,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,False,False,Click here to continue the story and make your...
1,3s1rvMFUweQ,GB,17.14.11,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632,25561,2294,2757,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,False,False,Musical guest Taylor Swift performs …Ready for...
2,n1WpP7iowLc,GB,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787420,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
3,PUTEiSjKwJU,GB,17.14.11,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833,193,12,37,https://i.ytimg.com/vi/PUTEiSjKwJU/default.jpg,False,False,False,Salford drew 4-4 against the Class of 92 and F...
4,rHwDegptbI4,GB,17.14.11,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25,2017-11-13T01:45:13.000Z,[none],9815,30,2,30,https://i.ytimg.com/vi/rHwDegptbI4/default.jpg,False,False,False,Dashcam captures truck's near miss with child ...

In [34]:
GB_category_map={1: 'Film & Animation', 2: 'Autos & Vehicles', 10: 'Music', 15: 'Pets & Animals', 17: 'Sports',
                 18: 'Short Movies', 19: 'Travel & Events', 20: 'Gaming', 21: 'Videoblogging',22: 'People & Blogs'
                 ,23: 'Comedy',24: 'Entertainment',25: 'News & Politics',26: 'Howto & Style',27:'Education',
                  28: 'Science & Technology',29: 'Nonprofits & Activism',30: 'Movies',31: 'Anime/Animation',
                  32: 'Action/Adventure',33: 'Classics',34: 'Comedy',35: 'Documentary',36: 'Drama',37: 'Family',
                 38: 'Foreign',39: 'Horror', 40: 'Sci-Fi/Fantasy',41: 'Thriller',42: 'Shorts',43: 'Shows',44: 'Trailers'}

GB_df['category_name']= GB_df['category_id'].map(GB_category_map)
GB_df.head()

,video_id,country,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,category_name
0,Jw1Y-zhQURU,GB,17.14.11,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515,55681,10247,9479,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,False,False,Click here to continue the story and make your...,Howto & Style
1,3s1rvMFUweQ,GB,17.14.11,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632,25561,2294,2757,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,False,False,Musical guest Taylor Swift performs …Ready for...,Entertainment
2,n1WpP7iowLc,GB,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787420,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,Music
3,PUTEiSjKwJU,GB,17.14.11,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833,193,12,37,https://i.ytimg.com/vi/PUTEiSjKwJU/default.jpg,False,False,False,Salford drew 4-4 against the Class of 92 and F...,Sports
4,rHwDegptbI4,GB,17.14.11,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25,2017-11-13T01:45:13.000Z,[none],9815,30,2,30,https://i.ytimg.com/vi/rHwDegptbI4/default.jpg,False,False,False,Dashcam captures truck's near miss with child ...,News & Politics

In [35]:
top_10_trending_cols = ["video_id", "title", "views", "category_id", "country"]
top_10_videos = GB_df[top_10_trending_cols].copy()
top_10_videos.drop_duplicates("video_id", inplace=True)
top_10_videos.set_index("video_id", inplace=False)
top10 = top_10_videos.sort_values(by='views', ascending=False).head(10)

top10

,video_id,title,views,category_id,country
3587,TyHvyGVs42U,"Luis Fonsi, Demi Lovato - Échame La Culpa",143408235,10,GB
32412,zEf423kYfqk,"Becky G, Natti Natasha - Sin Pijama (Official ...",88568646,10,GB
28479,WtE011iVx1Q,"Sebastián Yatra - Por Perro ft. Luis Figueroa,...",47669287,10,GB
31702,Ck4xHocysLw,Ozuna - Única (Video Oficial) 🐻 A U R A,42923278,10,GB
34463,7C2z4GqqS5E,BTS (방탄소년단) 'FAKE LOVE' Official MV,39349927,10,GB
19664,VTzD0jNdrmo,Rkm & Ken-Y ❌ Natti Natasha - Tonta [Official ...,39118664,10,GB
28458,i0p1bmr0EmE,TWICE What is Love? M/V,38873543,10,GB
3198,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,37736281,24,GB
19593,xpVfcZ0ZcFM,Drake - God’s Plan,33591858,10,GB
6,2Vv-BfVoq4g,Ed Sheeran - Perfect (Official Music Video),33523622,10,GB

In [36]:
top_viewed_videos_cols = ["video_id", "title", "likes", "trending_date", "category_id", "country"]
top_viewed_videos = GB_df[top_viewed_videos_cols].copy()
top_viewed_videos.drop_duplicates("video_id", inplace=True)
top_viewed_videos.set_index("video_id", inplace=False)
most_views = top_viewed_videos.sort_values(by='likes', ascending=False).head(10)
most_views

,video_id,title,likes,trending_date,category_id,country
34463,7C2z4GqqS5E,BTS (방탄소년단) 'FAKE LOVE' Official MV,3880074,18.19.05,10,GB
3587,TyHvyGVs42U,"Luis Fonsi, Demi Lovato - Échame La Culpa",2686169,17.01.12,10,GB
19593,xpVfcZ0ZcFM,Drake - God’s Plan,2152150,18.22.02,10,GB
2199,kTlv5_Bs8aw,BTS (방탄소년단) 'MIC Drop (Steve Aoki Remix)' Offi...,2055140,17.25.11,10,GB
21177,OK3GJ0WIQ8s,j-hope 'Daydream (백일몽)' MV,2050534,18.02.03,10,GB
32488,p8npDG2ulKQ,BTS (방탄소년단) LOVE YOURSELF 轉 Tear 'Singularity'...,1956210,18.07.05,10,GB
3198,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,1735902,17.30.11,24,GB
6,2Vv-BfVoq4g,Ed Sheeran - Perfect (Official Music Video),1634124,17.14.11,10,GB
28034,kX0vO4vlJuU,BTS (방탄소년단) 'Euphoria : Theme of LOVE YOURSELF...,1573003,18.06.04,10,GB
36739,D_6QmL6rExk,BTS (방탄소년단) 'FAKE LOVE' Official MV (Extended ...,1437859,18.02.06,10,GB

In [37]:
comments_cols = ["video_id", "title", "comment_count", "category_id","country"]
top_comments = GB_df[comments_cols].copy()
top_comments.drop_duplicates("video_id", inplace=True)
top_comments.set_index("video_id", inplace=False)
top_comments = top_comments.sort_values(by='comment_count', ascending=False).head(10)
top_comments

,video_id,title,comment_count,category_id,country
9993,QwZT7T-TXT0,So Sorry.,733371,24,GB
34463,7C2z4GqqS5E,BTS (방탄소년단) 'FAKE LOVE' Official MV,692311,10,GB
4593,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,462108,24,GB
16389,_5d-sQ7Fh5M,LOGAN PAUL IS BACK!,400416,24,GB
2199,kTlv5_Bs8aw,BTS (방탄소년단) 'MIC Drop (Steve Aoki Remix)' Offi...,395562,10,GB
21177,OK3GJ0WIQ8s,j-hope 'Daydream (백일몽)' MV,387384,10,GB
13992,oWjxSkJpxFU,Suicide: Be Here Tomorrow.,363140,29,GB
32488,p8npDG2ulKQ,BTS (방탄소년단) LOVE YOURSELF 轉 Tear 'Singularity'...,285591,10,GB
3198,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,241237,24,GB
15642,qtTM2YV3bI8,Lucas Lucco e Pabllo Vittar - Paraíso,237473,10,GB

In [62]:
category_cols = ["category_name","country"]
category_counts = GB_df[category_cols].copy()

GB_df.groupby(['category_name']).size()
GB_df.groupby(['category_name']).size().reset_index(name='number_of_videos')

            category_name  number_of_videos
0        Autos & Vehicles               144
1                  Comedy              1828
2               Education               457
3           Entertainment              9124
4        Film & Animation              2577
5                  Gaming              1788
6           Howto & Style              1928
7                   Music             13754
8         News & Politics              1225
9   Nonprofits & Activism                90
10         People & Blogs              2926
11         Pets & Animals               534
12   Science & Technology               518
13                  Shows                20
14                 Sports              1907
15        Travel & Events                96

In [74]:
# CREATING A FINAL DATAFRAME WITH THE CLEANED UP DATAFRAMES
final_df = pd.concat([clean_cavideos_df, USvideos_df, GB_df])

final_df

,video_id,country,title,channel_title,category_id,views,likes,dislikes,comment_count,trending_date,publish_time,tags,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,category_name
0,n1WpP7iowLc,CA,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,17158579,787425,43420,125882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0dBIkQ4Mz1M,CA,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,1014651,127794,1688,13030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5qpjK5DgCt4,CA,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,3191434,146035,5339,8181,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,d380meD0W0M,CA,I Dare You: GOING BALD!?,nigahiga,24,2095828,132239,1989,17518,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2Vv-BfVoq4g,CA,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,33523622,1634130,21082,85067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38911,l884wKofd54,GB,Enrique Iglesias - MOVE TO MIAMI (Official Vid...,EnriqueIglesiasVEVO,10,25066952,268088,12783,9933,18.14.06,2018-05-09T07:00:01.000Z,"Enrique Iglesias feat. Pitbull|""MOVE TO MIAMI""...",https://i.ytimg.com/vi/l884wKofd54/default.jpg,False,False,False,NEW SONG - MOVE TO MIAMI feat. Pitbull (Click ...,Music
38912,IP8k2xkhOdI,GB,Jacob Sartorius - Up With It (Official Music V...,Jacob Sartorius,10,1492219,61998,13781,24330,18.14.06,2018-05-11T17:09:16.000Z,"jacob sartorius|""jacob""|""up with it""|""jacob sa...",https://i.ytimg.com/vi/IP8k2xkhOdI/default.jpg,False,False,False,THE OFFICIAL UP WITH IT MUSIC VIDEO!Get my new...,Music
38913,Il-an3K9pjg,GB,Anne-Marie - 2002 [Official Video],Anne-Marie,10,29641412,394830,8892,19988,18.14.06,2018-05-08T11:05:08.000Z,"anne|""marie""|""anne-marie""|""2002""|""two thousand...",https://i.ytimg.com/vi/Il-an3K9pjg/default.jpg,False,False,False,Get 2002 by Anne-Marie HERE ▶ http://ad.gt/200...,Music
38914,-DRsfNObKIQ,GB,Eleni Foureira - Fuego - Cyprus - LIVE - First...,Eurovision Song Contest,24,14317515,151870,45875,26766,18.14.06,2018-05-08T20:32:32.000Z,"Eurovision Song Contest|""2018""|""Lisbon""|""Cypru...",https://i.ytimg.com/vi/-DRsfNObKIQ/default.jpg,False,False,False,Eleni Foureira represented Cyprus at the first...,Entertainment
38915,4YFo4bdMO8Q,GB,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,SuperDuperKyle,10,607552,18271,274,1423,18.14.06,2018-05-11T04:06:35.000Z,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",https://i.ytimg.com/vi/4YFo4bdMO8Q/default.jpg,False,False,False,Debut album 'Light of Mine' out now: http://ky...,Music

In [75]:
final_df.to_csv('Data/final.csv')

In [76]:
final_df.count()

video_id                  120746
country                   120746
title                     120746
channel_title             120746
category_id               120746
views                     120746
likes                     120746
dislikes                  120746
comment_count             120746
trending_date              79865
publish_time               79865
tags                       79865
thumbnail_link             79865
comments_disabled          79865
ratings_disabled           79865
video_error_or_removed     79865
description                78683
category_name              79865
dtype: int64

### LOAD TO MONGODB

In [78]:
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

In [79]:
db = client.youtubeDB

In [80]:
db.videos.insert_many(final_df.to_dict('records'))

In [81]:
db.videos.find()