In [4]:
import pandas as pd
from sqlalchemy import create_engine
import json

In [5]:
GBvideos_file = "GB/GBvideos.csv"
GB_videos = pd.read_csv(GBvideos_file)
GB_videos.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,Jw1Y-zhQURU,17.14.11,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515,55681,10247,9479,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,False,False,Click here to continue the story and make your...
1,3s1rvMFUweQ,17.14.11,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632,25561,2294,2757,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,False,False,Musical guest Taylor Swift performs …Ready for...
2,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787420,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
3,PUTEiSjKwJU,17.14.11,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833,193,12,37,https://i.ytimg.com/vi/PUTEiSjKwJU/default.jpg,False,False,False,Salford drew 4-4 against the Class of 92 and F...
4,rHwDegptbI4,17.14.11,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25,2017-11-13T01:45:13.000Z,[none],9815,30,2,30,https://i.ytimg.com/vi/rHwDegptbI4/default.jpg,False,False,False,Dashcam captures truck's near miss with child ...

In [6]:
GB_videos.columns

Index(['video_id', 'trending_date', 'title', 'channel_title', 'category_id',
       'publish_time', 'tags', 'views', 'likes', 'dislikes', 'comment_count',
       'thumbnail_link', 'comments_disabled', 'ratings_disabled',
       'video_error_or_removed', 'description'],
      dtype='object')

In [7]:
GB_json_file = "GB/GB_category_id.json"
type(GB_json_file)

str

In [8]:
GB_json_df=pd.read_json(GB_json_file)
GB_json_df.head()

,kind,etag,items
0,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
1,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
2,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
3,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
4,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."

In [9]:
list_countries = ["GB/GB_category_id.json"]
category = []

In [10]:
for country in list_countries:
    json_data = json.load(open(country,'r'))
    for data in json_data['items']:
        category.append([data['id'],data['snippet']['title']])

category

[['1', 'Film & Animation'],
 ['2', 'Autos & Vehicles'],
 ['10', 'Music'],
 ['15', 'Pets & Animals'],
 ['17', 'Sports'],
 ['18', 'Short Movies'],
 ['19', 'Travel & Events'],
 ['20', 'Gaming'],
 ['21', 'Videoblogging'],
 ['22', 'People & Blogs'],
 ['23', 'Comedy'],
 ['24', 'Entertainment'],
 ['25', 'News & Politics'],
 ['26', 'Howto & Style'],
 ['27', 'Education'],
 ['28', 'Science & Technology'],
 ['30', 'Movies'],
 ['31', 'Anime/Animation'],
 ['32', 'Action/Adventure'],
 ['33', 'Classics'],
 ['34', 'Comedy'],
 ['35', 'Documentary'],
 ['36', 'Drama'],
 ['37', 'Family'],
 ['38', 'Foreign'],
 ['39', 'Horror'],
 ['40', 'Sci-Fi/Fantasy'],
 ['41', 'Thriller'],
 ['42', 'Shorts'],
 ['43', 'Shows'],
 ['44', 'Trailers']]

In [11]:
gb_cols = ['video_id', 'trending_date', 'title', 'channel_title', 'category_id',
       'publish_time', 'tags', 'views', 'likes', 'dislikes', 'comment_count',
       'thumbnail_link', 'comments_disabled', 'ratings_disabled',
       'video_error_or_removed', 'description']
GB_df = GB_videos[gb_cols].copy()
GB_df.insert(1,'country','GB')
GB_df.head()

,video_id,country,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,Jw1Y-zhQURU,GB,17.14.11,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515,55681,10247,9479,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,False,False,Click here to continue the story and make your...
1,3s1rvMFUweQ,GB,17.14.11,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632,25561,2294,2757,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,False,False,Musical guest Taylor Swift performs …Ready for...
2,n1WpP7iowLc,GB,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787420,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
3,PUTEiSjKwJU,GB,17.14.11,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833,193,12,37,https://i.ytimg.com/vi/PUTEiSjKwJU/default.jpg,False,False,False,Salford drew 4-4 against the Class of 92 and F...
4,rHwDegptbI4,GB,17.14.11,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25,2017-11-13T01:45:13.000Z,[none],9815,30,2,30,https://i.ytimg.com/vi/rHwDegptbI4/default.jpg,False,False,False,Dashcam captures truck's near miss with child ...

In [17]:
GB_category_map={1: 'Film & Animation', 2: 'Autos & Vehicles', 10: 'Music', 15: 'Pets & Animals', 17: 'Sports',
                 18: 'Short Movies', 19: 'Travel & Events', 20: 'Gaming', 21: 'Videoblogging',22: 'People & Blogs'
                 ,23: 'Comedy',24: 'Entertainment',25: 'News & Politics',26: 'Howto & Style',27:'Education',
                  28: 'Science & Technology',29: 'Nonprofits & Activism',30: 'Movies',31: 'Anime/Animation',
                  32: 'Action/Adventure',33: 'Classics',34: 'Comedy',35: 'Documentary',36: 'Drama',37: 'Family',
                 38: 'Foreign',39: 'Horror', 40: 'Sci-Fi/Fantasy',41: 'Thriller',42: 'Shorts',43: 'Shows',44: 'Trailers'}

GB_df['category_name']= GB_df['category_id'].map(GB_category_map)
GB_df.head()

,video_id,country,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,category_name
0,Jw1Y-zhQURU,GB,17.14.11,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515,55681,10247,9479,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,False,False,Click here to continue the story and make your...,Howto & Style
1,3s1rvMFUweQ,GB,17.14.11,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632,25561,2294,2757,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,False,False,Musical guest Taylor Swift performs …Ready for...,Entertainment
2,n1WpP7iowLc,GB,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787420,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,Music
3,PUTEiSjKwJU,GB,17.14.11,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833,193,12,37,https://i.ytimg.com/vi/PUTEiSjKwJU/default.jpg,False,False,False,Salford drew 4-4 against the Class of 92 and F...,Sports
4,rHwDegptbI4,GB,17.14.11,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25,2017-11-13T01:45:13.000Z,[none],9815,30,2,30,https://i.ytimg.com/vi/rHwDegptbI4/default.jpg,False,False,False,Dashcam captures truck's near miss with child ...,News & Politics

In [13]:
top_10_trending_cols = ["video_id", "title", "views", "category_id", "country"]
top_10_videos = GB_df[top_10_trending_cols].copy()
top_10_videos.drop_duplicates("video_id", inplace=True)
top_10_videos.set_index("video_id", inplace=False)
top10 = top_10_videos.sort_values(by='views', ascending=False).head(10)

top10

,video_id,title,views,category_id,country
3587,TyHvyGVs42U,"Luis Fonsi, Demi Lovato - Échame La Culpa",143408235,10,GB
32412,zEf423kYfqk,"Becky G, Natti Natasha - Sin Pijama (Official ...",88568646,10,GB
28479,WtE011iVx1Q,"Sebastián Yatra - Por Perro ft. Luis Figueroa,...",47669287,10,GB
31702,Ck4xHocysLw,Ozuna - Única (Video Oficial) 🐻 A U R A,42923278,10,GB
34463,7C2z4GqqS5E,BTS (방탄소년단) 'FAKE LOVE' Official MV,39349927,10,GB
19664,VTzD0jNdrmo,Rkm & Ken-Y ❌ Natti Natasha - Tonta [Official ...,39118664,10,GB
28458,i0p1bmr0EmE,TWICE What is Love? M/V,38873543,10,GB
3198,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,37736281,24,GB
19593,xpVfcZ0ZcFM,Drake - God’s Plan,33591858,10,GB
6,2Vv-BfVoq4g,Ed Sheeran - Perfect (Official Music Video),33523622,10,GB

In [14]:
top_viewed_videos_cols = ["video_id", "title", "likes", "trending_date", "category_id", "country"]
top_viewed_videos = GB_df[top_viewed_videos_cols].copy()
top_viewed_videos.drop_duplicates("video_id", inplace=True)
top_viewed_videos.set_index("video_id", inplace=False)
most_views = top_viewed_videos.sort_values(by='likes', ascending=False).head(10)
most_views

,video_id,title,likes,trending_date,category_id,country
34463,7C2z4GqqS5E,BTS (방탄소년단) 'FAKE LOVE' Official MV,3880074,18.19.05,10,GB
3587,TyHvyGVs42U,"Luis Fonsi, Demi Lovato - Échame La Culpa",2686169,17.01.12,10,GB
19593,xpVfcZ0ZcFM,Drake - God’s Plan,2152150,18.22.02,10,GB
2199,kTlv5_Bs8aw,BTS (방탄소년단) 'MIC Drop (Steve Aoki Remix)' Offi...,2055140,17.25.11,10,GB
21177,OK3GJ0WIQ8s,j-hope 'Daydream (백일몽)' MV,2050534,18.02.03,10,GB
32488,p8npDG2ulKQ,BTS (방탄소년단) LOVE YOURSELF 轉 Tear 'Singularity'...,1956210,18.07.05,10,GB
3198,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,1735902,17.30.11,24,GB
6,2Vv-BfVoq4g,Ed Sheeran - Perfect (Official Music Video),1634124,17.14.11,10,GB
28034,kX0vO4vlJuU,BTS (방탄소년단) 'Euphoria : Theme of LOVE YOURSELF...,1573003,18.06.04,10,GB
36739,D_6QmL6rExk,BTS (방탄소년단) 'FAKE LOVE' Official MV (Extended ...,1437859,18.02.06,10,GB

In [15]:
comments_cols = ["video_id", "title", "comment_count", "category_id","country"]
top_comments = GB_df[comments_cols].copy()
top_comments.drop_duplicates("video_id", inplace=True)
top_comments.set_index("video_id", inplace=False)
top_comments = top_comments.sort_values(by='comment_count', ascending=False).head(10)
top_comments

,video_id,title,comment_count,category_id,country
9993,QwZT7T-TXT0,So Sorry.,733371,24,GB
34463,7C2z4GqqS5E,BTS (방탄소년단) 'FAKE LOVE' Official MV,692311,10,GB
4593,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,462108,24,GB
16389,_5d-sQ7Fh5M,LOGAN PAUL IS BACK!,400416,24,GB
2199,kTlv5_Bs8aw,BTS (방탄소년단) 'MIC Drop (Steve Aoki Remix)' Offi...,395562,10,GB
21177,OK3GJ0WIQ8s,j-hope 'Daydream (백일몽)' MV,387384,10,GB
13992,oWjxSkJpxFU,Suicide: Be Here Tomorrow.,363140,29,GB
32488,p8npDG2ulKQ,BTS (방탄소년단) LOVE YOURSELF 轉 Tear 'Singularity'...,285591,10,GB
3198,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,241237,24,GB
15642,qtTM2YV3bI8,Lucas Lucco e Pabllo Vittar - Paraíso,237473,10,GB

In [18]:
category_cols = ["category_name","country"]
category_counts = GB_df[category_cols].copy()

GB_df.groupby(['category_name']).size()
GB_df.groupby(['category_name']).size().reset_index(name='number_of_videos')

#category_counts.merge(counts_cat, how='left', on='index')

            category_name  number_of_videos
0        Autos & Vehicles               144
1                  Comedy              1828
2               Education               457
3           Entertainment              9124
4        Film & Animation              2577
5                  Gaming              1788
6           Howto & Style              1928
7                   Music             13754
8         News & Politics              1225
9   Nonprofits & Activism                90
10         People & Blogs              2926
11         Pets & Animals               534
12   Science & Technology               518
13                  Shows                20
14                 Sports              1907
15        Travel & Events                96